# Generated by Django 5.1.6 on 2025-03-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('occupied', models.BooleanField(default=False)),
            ],
        ),
    ]
